// planes.js - Datos de los planes de entrenamiento
const planes = {
    "30min":[
        [["Lunes","5 Series de 1 min corriendo + 2 min caminando"],["Martes","5 Series de 1 min corriendo + 2 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 1 min corriendo + 2 min caminando"],["Viernes","6 Series de 1 min corriendo + 2 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 1 min corriendo + 2 min caminando"]],
        [["Lunes","5 Series de 1.5 min corriendo + 2 min caminando"],["Martes","5 Series de 1.5 min corriendo + 2 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 1.5 min corriendo + 2 min caminando"],["Viernes","6 Series de 1.5 min corriendo + 2 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 1.5 min corriendo + 2 min caminando"]],
        [["Lunes","5 Series de 2 min corriendo + 2 min caminando"],["Martes","5 Series de 2 min corriendo + 2 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 2 min corriendo + 2 min caminando"],["Viernes","6 Series de 2 min corriendo + 2 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 2 min corriendo + 2 min caminando"]],
        [["Lunes","5 Series de 3 min corriendo + 2 min caminando"],["Martes","5 Series de 3 min corriendo + 2 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 3 min corriendo + 2 min caminando"],["Viernes","6 Series de 3 min corriendo + 2 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 3 min corriendo + 2 min caminando"]],
        [["Lunes","Progresivo hasta 12 min"],["Martes","Progresivo hasta 12 min"],["Miércoles","Descanso"],["Jueves","Progresivo hasta 12 min"],["Viernes","Progresivo hasta 12 min"],["Sábado","Descanso"],["Domingo","Progresivo hasta 12 min"]],
        [["Lunes","Hasta 22 min continuos"],["Martes","Hasta 22 min continuos"],["Miércoles","Descanso"],["Jueves","Hasta 22 min continuos"],["Viernes","Hasta 22 min continuos"],["Sábado","Descanso"],["Domingo","Hasta 22 min continuos"]],
        [["Luenes","25 min continuos"],["Martes","25 min continuos"],["Miércoles","Descanso"],["Jueves","25 min continuos"],["Viernes","25 min continuos"],["Sábado","Descanso"],["Domingo","25 min continuos"]],
        [["Lunes","30 min continuos"],["Martes","30 min continuos"],["Miércoles","Descanso"],["Jueves","30 min continuos"],["Viernes","30 min continuos"],["Sábado","Descanso"],["Domingo","30 min continuos"]]
    ],
    "5k":[
        [["Lunes","2 km suaves + caminar"],["Martes","2 km suaves + caminar"],["Miércoles","Descanso"],["Jueves","2 km suaves + caminar"],["Viernes","2 km suaves + caminar"],["Sábado","Descanso"],["Domingo","2 km suaves + caminar"]],
        [["Lunes","3 km con pausas"],["Martes","3 km con pausas"],["Miércoles","Descanso"],["Jueves","3 km con pausas"],["Viernes","3 km con pausas"],["Sábado","Descanso"],["Domingo","3 km con pausas"]],
        [["Lunes","3.5 km seguidos, ritmo suave"],["Martes","3.5 km seguidos, ritmo suave"],["Miércoles","Descanso"],["Jueves","3.5 km seguidos, ritmo suave"],["Viernes","3.5 km seguidos, ritmo suave"],["Sábado","Descanso"],["Domingo","3.5 km seguidos, ritmo suave"]],
        [["Lunes","4 km + 1 km más rápido"],["Martes","4 km + 1 km más rápido"],["Miércoles","Descanso"],["Jueves","4 km + 1 km más rápido"],["Viernes","4 km + 1 km más rápido"],["Sábado","Descanso"],["Domingo","4 km + 1 km más rápido"]],
        [["Lunes","5 km intercalando ritmos"],["Martes","5 km intercalando ritmos"],["Miércoles","Descanso"],["Jueves","5 km intercalando ritmos"],["Viernes","5 km intercalando ritmos"],["Sábado","Descanso"],["Domingo","5 km intercalando ritmos"]],
        [["Lunes","5 km seguidos cómodamente"],["Martes","5 km seguidos cómodamente"],["Miércoles","Descanso"],["Jueves","5 km seguidos cómodamente"],["Viernes","5 km seguidos cómodamente"],["Sábado","Descanso"],["Domingo","5 km seguidos cómodamente"]]
    ],
    "fartlek":[
        [["Lunes","2 km corriendo + 1 km fartlek suave"],["Martes","2 km corriendo + 1 km fartlek suave"],["Miércoles","Descanso"],["Jueves","2 km corriendo + 1 km fartlek suave"],["Viernes","2 km corriendo + 1 km fartlek suave"],["Sábado","Descanso"],["Domingo","2 km corriendo + 1 km fartlek suave"]],
        [["Lunes","3 km corriendo + 1 km fartlek intercalando"],["Martes","3 km corriendo + 1 km fartlek intercalando"],["Miércoles","Descanso"],["Jueves","3 km corriendo + 1 km fartlek intercalando"],["Viernes","3 km corriendo + 1 km fartlek intercalando"],["Sábado","Descanso"],["Domingo","3 km corriendo + 1 km fartlek intercalando"]],
        [["Lunes","4 km con cambios de ritmo frecuentes"],["Martes","4 km con cambios de ritmo frecuentes"],["Miércoles","Descanso"],["Jueves","4 km con cambios de ritmo frecuentes"],["Viernes","4 km con cambios de ritmo frecuentes"],["Sábado","Descanso"],["Domingo","4 km con cambios de ritmo frecuentes"]],
        [["Lunes","5 km con 3 segmentos fartlek rápidos"],["Martes","5 km con 3 segmentos fartlek rápidos"],["Miércoles","Descanso"],["Jueves","5 km con 3 segmentos fartlek rápidos"],["Viernes","5 km con 3 segmentos fartlek rápidos"],["Sábado","Descanso"],["Domingo","5 km con 3 segmentos fartlek rápidos"]],
        [["Lunes","5 km continuos con variación de ritmo"],["Martes","5 km continuos con variación de ritmo"],["Miércoles","Descanso"],["Jueves","5 km continuos con variación de ritmo"],["Viernes","5 km continuos con variación de ritmo"],["Sábado","Descanso"],["Domingo","5 km continuos con variación de ritmo"]],
        [["Lunes","6 km con 4 cambios de ritmo intensos"],["Martes","6 km con 4 cambios de ritmo intensos"],["Miércoles","Descanso"],["Jueves","6 km con 4 cambios de ritmo intensos"],["Viernes","6 km con 4 cambios de ritmo intensos"],["Sábado","Descanso"],["Domingo","6 km con 4 cambios de ritmo intensos"]]
    ],
    "hiit":[
        [["Lunes","5 Series de 30 seg fuerte + 1 min caminando"],["Martes","5 Series de 30 seg fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 30 seg fuerte + 1 min caminando"],["Viernes","6 Series de 30 seg fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 30 seg fuerte + 1 min caminando"]],
        [["Lunes","5 Series de 40 seg fuerte + 1 min caminando"],["Martes","6 Series de 40 seg fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","5 Series de 40 seg fuerte + 1 min caminando"],["Viernes","6 Series de 40 seg fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 40 seg fuerte + 1 min caminando"]],
        [["Lunes","6 Series de 45 seg fuerte + 1 min caminando"],["Martes","8 Series de 45 seg fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","6 Series de 45 seg fuerte + 1 min caminando"],["Viernes","8 Series de 45 seg fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","6 Series de 45 seg fuerte + 1 min caminando"]],
        [["Lunes","8 Series 50 seg fuerte + 1 min caminando"],["Martes","8 Series 50 seg fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","8 Series 50 seg fuerte + 1 min caminando"],["Viernes","8 Series 50 seg fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","8 Series 50 seg fuerte + 1 min caminando"]],
        [["Lunes","8 Series 1 min fuerte + 1 min caminando"],["Martes","8 Series 1 min fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","8 Series 1 min fuerte + 1 min caminando"],["Viernes","8 Series 1 min fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","8 Series 1 min fuerte + 1 min caminando"]],
        [["Lunes","10 Series 1 min fuerte + 1 min caminando"],["Martes","10 Series 1 min fuerte + 1 min caminando"],["Miércoles","Descanso"],["Jueves","10 Series 1 min fuerte + 1 min caminando"],["Viernes","10 Series 1 min fuerte + 1 min caminando"],["Sábado","Descanso"],["Domingo","10 Series 1 min fuerte + 1 min caminando"]]
    ],
    "trail":[
        [["Lunes","Fuerza básica: 3x10 sentadillas + 3x10 zancadas + 20 min caminata en sendero"],["Martes","3 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","20 min alternando 2 min trote + 1 min caminar en sendero"],["Viernes","30 min caminata en sendero con desnivel suave"],["Sábado","Descanso"],["Domingo","5 km caminata/trote en sendero natural"]],
        [["Lunes","Fuerza: 3x12 sentadillas + 3x10 zancadas + 10 min escalones"],["Martes","4 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","25 min alternando 3 min trote + 1 min caminar en sendero"],["Viernes","35 min trote suave en sendero con cuestas cortas"],["Sábado","Descanso"],["Domingo","6 km trote suave en sendero natural"]],
        [["Lunes","Fuerza trail: 4x10 sentadillas + 4x10 zancadas + 15 min subida/bajada escalones"],["Martes","5 km carrera suave en sendero"],["Miércoles","Descanso"],["Jueves","5x2 min ritmo fuerte + 1 min trote suave en terreno variado"],["Viernes","5 km en sendero con desnivel moderado"],["Sábado","Descanso"],["Domingo","8 km carrera en sendero con terreno mixto"]],
        [["Lunes","Fuerza trail: 4x12 sentadillas + 4x10 zancadas + 6 cuestas de 30 seg"],["Martes","5 km carrera continua en sendero suave"],["Miércoles","Descanso"],["Jueves","6x2 min ritmo fuerte + 1 min recuperación en terreno irregular"],["Viernes","6 km en sendero con cuestas moderadas"],["Sábado","Descanso"],["Domingo","10 km carrera en sendero con desniveles variados"]],
        [["Lunes","Fuerza trail: 4x15 sentadillas + 4x12 zancadas + 8 cuestas de 40 seg"],["Martes","6 km carrera suave en sendero irregular"],["Miércoles","Descanso"],["Jueves","8x2 min fartlek en terreno variado: subida fuerte + bajada técnica"],["Viernes","7 km en sendero técnico con desniveles pronunciados"],["Sábado","Descanso"],["Domingo","12 km carrera en sendero con terreno técnico"]],
        [["Lunes","Fuerza trail: 5x12 sentadillas + 4x12 zancadas + 10 cuestas de 45 seg"],["Martes","7 km carrera continua en sendero irregular"],["Miércoles","Descanso"],["Jueves","6x3 min ritmo fuerte en subida + bajada técnica controlada"],["Viernes","8 km en sendero con desniveles y terreno técnico"],["Sábado","Descanso"],["Domingo","14 km carrera larga en sendero con terreno variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 10 cuestas de 1 min"],["Martes","7 km carrera suave en sendero técnico (trabajo de bajada)"],["Miércoles","Descanso"],["Jueves","8x3 min fartlek en terreno montañoso: subidas y bajadas continuas"],["Viernes","8 km en sendero de montaña con desnivel acumulado alto"],["Sábado","Descanso"],["Domingo","16 km carrera larga en terreno de montaña variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 12 cuestas de 1 min"],["Martes","8 km carrera suave en sendero técnico"],["Miércoles","Descanso"],["Jueves","10x2 min sprints en cuesta + bajada técnica controlada"],["Viernes","10 km en sendero accidentado con desniveles fuertes"],["Sábado","Descanso"],["Domingo","18 km carrera larga en terreno accidentado de montaña"]]
    ],
    "sobrepeso":[
        [["Lunes","10 min caminando + 1 min corriendo"],["Martes","10 min caminando + 1 min corriendo"],["Miércoles","Descanso"],["Jueves","10 min caminando + 1 min corriendo"],["Viernes","10 min caminando + 1 min corriendo"],["Sábado","Descanso"],["Domingo","10 min caminando + 1 min corriendo"]],
        [["Lunes","15 min caminando + 2 min corriendo"],["Martes","15 min caminando + 2 min corriendo"],["Miércoles","Descanso"],["Jueves","15 min caminando + 2 min corriendo"],["Viernes","15 min caminando + 2 min corriendo"],["Sábado","Descanso"],["Domingo","15 min caminando + 2 min corriendo"]],
        [["Lunes","20 min caminando + 3 min corriendo"],["Martes","20 min caminando + 3 min corriendo"],["Miércoles","Descanso"],["Jueves","20 min caminando + 3 min corriendo"],["Viernes","20 min caminando + 3 min corriendo"],["Sábado","Descanso"],["Domingo","20 min caminando + 3 min corriendo"]],
        [["Lunes","25 min caminando + 4 min corriendo"],["Martes","25 min caminando + 4 min corriendo"],["Miércoles","Descanso"],["Jueves","25 min caminando + 4 min corriendo"],["Viernes","25 min caminando + 4 min corriendo"],["Sábado","Descanso"],["Domingo","25 min caminando + 4 min corriendo"]],
        [["Lunes","30 min caminando + 5 min corriendo"],["Martes","30 min caminando + 5 min corriendo"],["Miércoles","Descanso"],["Jueves","30 min caminando + 5 min corriendo"],["Viernes","30 min caminando + 5 min corriendo"],["Sábado","Descanso"],["Domingo","30 min caminando + 5 min corriendo"]],
        [["Lunes","35 min caminando + 6 min corriendo"],["Martes","35 min caminando + 6 min corriendo"],["Miércoles","Descanso"],["Jueves","35 min caminando + 6 min corriendo"],["Viernes","35 min caminando + 6 min corriendo"],["Sábado","Descanso"],["Domingo","35 min caminando + 6 min corriendo"]]
    ]
};